name: App CI — merge v2

on:
  push:
    branches: [main]
    paths-ignore:
      - 'ci/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: chau11ece/proops2026-cicd-platform/.github/workflows/reusable-build.yml@v2
    secrets: inherit
    with:
      project-name: "proops2026-taskmanager"
      service-name: "scripts"

  deploy-dev:
    needs: build
    uses: chau11ece/proops2026-cicd-platform/.github/workflows/reusable-deploy.yml@v2
    secrets: inherit
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
      environment: dev
      project-name: "proops2026-taskmanager"
      service-name: "scripts"
